planner_node:
  ros__parameters:
    path_frame_id: base_link
    model_name: model.pt
    lookahead_distance: 1.5
    linear_max.vel: 1.0
    placenet_model_name: placenet.pt
    use_topomap: false
    use_zed: false
    topomap_dir_name: topomap
    placenet_delta: 10.0
    placenet_window_lower: -1
    placenet_window_upper: 2
    interval_ms: 100
