planner_node:
  ros__parameters:
    linear_max.vel: 1.0
    model_name: mlplanner.pt
    placenet_model_name: placenet.pt
    use_topomap: false
    use_zed: false
    topomap_dir_name: topomap
    placenet_delta: 10.0
    placenet_window_lower: -1
    placenet_window_upper: 2
    interval_ms: 100
