epochs: 200
batch_size: 16
learning_rate: 0.0002
num_workers: 8
weight_file: "hoge.pt"
chunk_size: 8
dataset_config: "dataset.yaml"

augment:
  crop: true
  randomshadow: true

randomshadow:
  p: 0.5
  high_ratio: [1.0, 2.0]
  low_ratio: [0.01, 0.5]
  left_low_ratio: [0.4, 0.6]
  left_high_ratio: [0.0, 0.2]
  right_low_ratio: [0.4, 0.6]
  right_high_ratio: [0.0, 0.2]
