epochs: 200
batch_size: 32
learning_rate: 0.0001
num_workers: 2
weight_file: "haruyama_course_diffusion.pt"

dataset:
  n_obs_steps: 2
  pred_horizon: 8
  action_dim: 1

vision:
  image_size: 224

augment:
  crop: true
  randomshadow: false

randomshadow:
  p: 0.5
  high_ratio: [1.0, 2.0]
  low_ratio: [0.01, 0.5]
  left_low_ratio: [0.4, 0.6]
  left_high_ratio: [0.0, 0.2]
  right_low_ratio: [0.4, 0.6]
  right_high_ratio: [0.0, 0.2]
